# Generated by Django 5.0 on 2023-12-07 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_drive', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NFiles',
            new_name='File',
        ),
        migrations.RenameModel(
            old_name='NUsers',
            new_name='NUser',
        ),
    ]
